name: ci
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14.20'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare demo-app
      run: |
        cd pizza-demo
        npm ci
    - name: Prepare lib
      run: |
        cd lib
        npm ci
    - name: Prepare root
      run: |
        npm ci
    - name: Execute tests with defaults
      run: |
        npm run serve-and-test:parallel
    - name: Execute only some tests
      run: |
        npm run serve-and-test:parallel:some
    - name: Execute tests with spec reporter
      run: |
        npm run serve-and-test:parallel:spec
    - name: Execute tests with junit reporter
      run: |
        npm run serve-and-test:parallel:junit
